application:
  address: localhost:3000

mysql:
  host: localhost
  user: root
  pass: passwd
  port: 3306
  db: enroll

redis:
  addr: localhost:6379
  password:
  db: 0

csv:
  uploaded: D:\\zed\\
  generated: D:\\Codes\\enroll\\generates\\