application:
  address: localhost:3000

mysql:
  host: gen8
  user: root
  pass: passwd
  port: 3306
  db: enroll

redis:
  addr: gen8:6379
  password: passwd
  db: 0

csv:
  example: D:\\Codes\\Enroll\\uploads\\example.csv
  uploaded: D:\\zed\\